travis:
  secure:
    BINSTAR_TOKEN: NgXjWsCldonQQ/lBFQ9IOplB6Qb8VGxSPFB8WfDjdulM46MHgJpJ7O016I6APvOcNJXTO0scQswFIww8iKM26pM4sidOyeVRxVXsrZNa9ihsGfkS7RTTmpbjPQY1e/V9oH6RbLUpQFu4dD3OZ32yjy8Tk5fZVhodPfZP6ImrpMbj2Tk7TrmZySv73XPG2X5dad6CWYiOawyXyA8D5fLAa3IFEzuWJxfAvUdUykdxK0tY/kCQkhaSu63HpcbASmoigSC+dZFbthUYe24cOLJnT2etg/sd2a9Ch1cAMhifsli9hSxBjSdCgNX+NydwDlxkNETVzqKhJWoA/AAN6iUq7U2gYSLcbIA9hz5ib85jB4ss05AzsR84WFM2Iz0DlukyQyE+qKoco9hGuzzgaaG9SXokzQjh+aEQGvujIz5rK6ksbE7uw7RlEpgYHTdSdYNiDjpNS3e2UFV4bF2BD1ygGZmJNEBiFcXnepE4vrafYoc8a0i8oIebNgzMPHPPndna76c2AEDHzMfq24v9VWe3ZURi9Yqp78wOilI9pTxqczlv9aYk+Dz3OOvuoRsYijf4vW7RazOnLOEm7f95/kc7oN7vaOD2SbnM+D4j23E3QfJL/YWMorIsHPCbsTjBM1TDA96PgQZ/vInkqsjFxQIMSJAQES+2gUHYeilg0CCQih4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
